version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment: 
    #   - MONGO_INITDB_ROOT_USERNAME=dude
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file: 
      - ./env/mongo.env
    # networks: (Not needed in compose)
    #   - goals-net

  backend:
    build: ./backend
    # build:  (verbose format for building)
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    volumes: 
      - logs:/app/logs
      - ./backend/:/app
      - /app/node_modules
    environment: 
      - MONGODB_USERNAME=dude
      - MONGODB_PASSWORD=secret
    ports:
      - "80:80"
    depends_on: 
      - mongodb

  frontend:
    build: ./frontend
    volumes: 
      - ./frontend/src:/app/src
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on: 
      - backend
    

# all named volumes need to be specified here
volumes:
  data:
  logs: